
[[Headline]]
name = "hl-Title"
text = "Settings"
pos = { x = 40, y = 40 }
width = 120 #optional
enabled = true #optional

[[Slider]]
name = "sl-Brightness"
pos = { x = 40, y = 80 }
label = "Brightness"
default = 0.3 #optional
min = 0.0 #optional
max = 1.0 #optional
labelWidth = 120 #optional
sliderWidth = 160 #optional

[[Slider]]
name = "sl-Width"
pos = { x = 40, y = 120 }
label = "Width"
default = 20 #optional
min = 1 #optional
max = 100 #optional
labelWidth = 120 #optional
sliderWidth = 160 #optional

[[Slider]]
name = "sl-Height"
pos = { x = 40, y = 160 }
label = "Height"
default = 60 #optional
min = 1 #optional
max = 100 #optional
labelWidth = 120 #optional
sliderWidth = 160 #optional


[[Headline]]
name = "hl-Parameters"
text = "Parameters"
pos = { x = 40, y = 240 }
width = 160 #optional
enabled = true #optional

[[VerticalSlider]]
name = "vs-Parameter0"
pos = { x = 40, y = 280 }
default = 0.2 #optional
min = 0.0 #optional
max = 1.0 #optional
labelHeight = 120 #optional

[[VerticalSlider]]
name = "vs-Parameter1"
pos = { x = 80, y = 280 }
default = 0.5 #optional
min = 0.0 #optional
max = 1.0 #optional
labelHeight = 120 #optional

[[VerticalSlider]]
name = "vs-Parameter2"
pos = { x = 120, y = 280 }
default = 0.8 #optional
min = 0.0 #optional
max = 1.0 #optional
labelHeight = 120 #optional


[[Headline]]
name = "hl-CheckBox"
text = "CheckBox"
pos = { x = 360, y = 40 }
width = 120 #optional
enabled = true #optional

[[CheckBox]]
name = "cb-Item0"
label = "Item 0"
pos = { x = 360, y = 80 }
default = true #optional
width = 160 #optional
enabled = true #optional

[[CheckBox]]
name = "cb-Item1"
label = "Item 1"
pos = { x = 360, y = 120 }
default = false #optional
width = 160 #optional
enabled = true #optional

[[CheckBox]]
name = "cb-Item2"
label = "Item 2"
pos = { x = 360, y = 160 }
default = false #optional
width = 160 #optional
enabled = true #optional


[[Headline]]
name = "hl-RadioButtons"
text = "OS"
pos = { x = 240, y = 240 }
width = 80 #optional
enabled = true #optional

[[RadioButtons]]
name = "rb-Options"
pos = { x = 240, y = 280 }
options = [ "Windows", "macOS", "Linux" ]
default = 1 #optional
width = 160 #optional
enabled = true #optional


[[TextBox]]
name = "tb-Name"
pos = { x = 400, y = 440 }
default = "Siv3D"
width = 160 #optional
maxChars = 8 #optional
enabled = true #optional


[[Headline]]
name = "hl-ColorPicker"
text = "Color"
pos = { x = 440, y = 240 }
width = 80 #optional
enabled = true #optional

[[ColorPicker]]
name = "cp-Options"
pos = { x = 440, y = 280 }
default = { h = 120, s = 0.5, v = 0.8 } #optional
enabled = true #optional


[[Button]]
name = "bt-OK"
label = "OK"
pos = { x = 120, y = 440 }
width = 160 #optional
enabled = true #optional

[[Button]]
name = "bt-Cancel"
label = "Cancel"
pos = { x = 120, y = 480 }
width = 160 #optional
enabled = true #optional

